---

- name: Add docker repo
  yum_repository:
    name: Docker-CE-stable
    state: present
    description: Docker Community Edition repository
    baseurl: "https://download.docker.com/linux/centos/7/{{ ansible_architecture }}/stable"
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true

- name: Install docker
  yum:
    state: present
    update_cache: true
    name:
      - lvm2
      - python-docker-py
      - yum-utils
      - device-mapper-persistent-data
      - docker-ce

- name: Edit systemd unit file
  replace:
    path: "{{ docker.config.systemd.unit }}"
    regexp: "^ExecStart=.*"
    replace: "ExecStart=/usr/bin/dockerd"
    backup: true
  notify:
    - daemon_reload
    - docker_restart

- meta: flush_handlers

- name: Create docker directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/docker
    - /data/dockershared

- name: Create docker config file
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker.config.daemon | to_nice_json }}"
  notify:
    - docker_restart

- meta: flush_handlers

- name: Enable docker service
  service:
    name: docker
    state: started
    enabled: true
